const Permissions = {
    CREATE_USER: 'CREATE_USER',
    READ_USER:'READ_USER',
    UPDATE_USER:'UPDATE_USER',
    DELETE_USER:'DELETE_USER',
    CREATE_ARTIST: 'CREATE_ARTIST',
    READ_ARTIST:'READ_ARTIST',
    UPDATE_ARTIST:'UPDATE_ARTIST',
    DELETE_ARTIST:'DELETE_ARTIST',
    CREATE_SONG: 'CREATE_SONG',
    READ_SONG:'READ_SONG',
    UPDATE_SONG:'UPDATE_SONG',
    DELETE_SONG:'DELETE_SONG'
}

module.exports = Permissions;